km841/DX11_3D_1TEAM

OurGame/Resources/Shader/final.fx

Fixed light power

---

OurGame/Client/Client.vcxproj
OurGame/Client/Client.vcxproj.filters
OurGame/Client/GrandmaBossMap.cpp
OurGame/Client/PlayerMoveScript.cpp
OurGame/Client/PlayerMoveScript.h
OurGame/Client/PrefabManager.cpp
OurGame/Engine/CollisionManager.h
OurGame/Engine/RigidBody.cpp
OurGame/Engine/RigidBody.h
OurGame/Engine/Transform.cpp
OurGame/Resources/Shader/sampling.fx

- RigidBody의 Clone에서 물리 오브젝트를 생성 후 다시 위치값을 세팅해주지 않아서 GetPrefab의 반환 오브젝트의 위치값이 초기화되지 않았던 버그 수정

Prefab bug fix

---

OurGame/Client/GrandmaBossMap.cpp
OurGame/Client/PrefabManager.cpp
OurGame/Engine/Material.cpp
OurGame/Engine/Resources.cpp
OurGame/Resources/Shader/combine.fx
OurGame/Resources/Shader/deferred.fx
OurGame/Resources/Shader/lighting.fx
OurGame/Resources/Shader/player_slash.fx
OurGame/Resources/Shader/sampling.fx

Apply partial bloom

---

OurGame/Client/GrandmaBossMap.cpp

Delete test code

---

OurGame/Client/GrandmaBossMap.cpp
OurGame/Engine/Material.cpp
OurGame/Engine/ParticleSystem.cpp
OurGame/Engine/RenderManager.cpp
OurGame/Engine/RenderManager.h
OurGame/Engine/Shader.cpp
OurGame/Resources/Shader/compute_downscale.fx
OurGame/Resources/Shader/hdr.fx

Fixed HDR & Particle system

---

OurGame/Client/CameraMoveScript.cpp

Fix camera move script

---

OurGame/Client/GrandmaBossMap.cpp
OurGame/Engine/Engine.cpp
OurGame/Engine/Engine.vcxproj
OurGame/Engine/Engine.vcxproj.filters
OurGame/Engine/EnginePch.h
OurGame/Engine/FBXLoader.cpp
OurGame/Engine/FontManager.cpp
OurGame/Engine/FontManager.h
OurGame/Engine/GraphicsCore.cpp
OurGame/Engine/GraphicsCore.h
OurGame/Engine/Material.h
OurGame/Engine/MeshRenderer.cpp
OurGame/Engine/Shader.cpp
OurGame/Engine/Shader.h

Apply clamp & wrap sampler type

Apply clamp & wrap sampler type

---

OurGame/Client/GrandmaBossMap.cpp
OurGame/Engine/Engine.cpp
OurGame/Engine/Engine.vcxproj
OurGame/Engine/Engine.vcxproj.filters
OurGame/Engine/MultiRenderTarget.h
OurGame/Engine/RenderManager.cpp
OurGame/Engine/RenderManager.h
OurGame/Engine/Resources.cpp
OurGame/Engine/Scene.cpp
OurGame/Resources/Shader/rimlighting.fx

Implement rim lighting

---

OurGame/Engine/Material.h
OurGame/Engine/Shader.cpp
OurGame/Engine/Shader.h

Implement resterizer state setting

Implement resterizer state setting

---

OurGame/Client/Right2Map.cpp
OurGame/Engine/Engine.cpp
OurGame/Engine/Engine.vcxproj
OurGame/Engine/Engine.vcxproj.filters
OurGame/Engine/ImageFilter.h
OurGame/Engine/Material.h
OurGame/Engine/RenderManager.cpp
OurGame/Engine/RenderManager.h
OurGame/Engine/Resources.cpp
OurGame/Resources/Shader/deferred.fx
OurGame/Resources/Shader/downscale.fx
OurGame/Resources/Shader/hdr.fx
OurGame/Resources/Shader/lightblend.fx
OurGame/Resources/Shader/lighting.fx

Fixed select bloom

---

OurGame/Client/Right2Map.cpp
OurGame/Engine/Material.h
OurGame/Engine/RenderManager.cpp
OurGame/Engine/Resources.h
OurGame/Engine/Shader.cpp
OurGame/Engine/Types.h
OurGame/Resources/Shader/deferred.fx

Implement uv tiling options

---

OurGame/Client/Map.cpp
OurGame/Engine/Tool.cpp
OurGame/Engine/Tool.h
OurGame/Engine/Transform.cpp
OurGame/Engine/Transform.h

Implement undo/redo in tool

---

OurGame/Client/CorridorRightMap.cpp
OurGame/Client/RightMap.cpp
OurGame/Client/TitleScene.cpp
OurGame/Engine/RenderManager.cpp

- CorridorRightMap, RightMap 스케일 수정

Repair maps

---

OurGame/Client/Application.cpp
OurGame/Client/CorridorRightMap.cpp
OurGame/Client/CorridorRightMap.h

CorridorRightMap 네임스페이스 적용

---

OurGame/Client/RightSecretPassageMap.cpp
OurGame/Client/RightSecretPassageMap.h

RightSecretMap 버그 수정

---

OurGame/Client/HallColliderCheckMap.cpp
OurGame/Client/Map.cpp
OurGame/Client/Map.h
OurGame/Client/TestAnimationScript.cpp
OurGame/Client/imgui.ini
OurGame/Engine/Animator.cpp
OurGame/Engine/Animator.h
OurGame/Engine/Mesh.h
OurGame/Engine/Tool.cpp
OurGame/Engine/Tool.h

Implement animation tool

---

OurGame/Client/HallColliderCheckMap.cpp
OurGame/Client/Player.cpp
OurGame/Client/Player.h
OurGame/Client/PlayerMoveScript.cpp
OurGame/Engine/Animator.cpp
OurGame/Engine/RigidBody.cpp
OurGame/Engine/RigidBody.h
OurGame/Engine/Tool.cpp
OurGame/Engine/Transform.cpp

Implement kinematic actor functions

---

OurGame/Client/Application.cpp
OurGame/Client/Client.vcxproj
OurGame/Client/Client.vcxproj.filters
OurGame/Client/PhysicsTestScene.cpp
OurGame/Client/PhysicsTestScene.h
OurGame/Client/TitleScene.cpp
OurGame/Engine/EnumDefine.h

PhysX Test Scene 추가

---

OurGame/Client/HallColliderCheckMap.cpp
OurGame/Client/Map.cpp
OurGame/Client/Map.h
OurGame/Client/Monster_Player_TestScene.cpp
OurGame/Client/TitleScene.cpp
OurGame/Client/imgui.ini
OurGame/Engine/Timer.h
OurGame/Engine/Tool.cpp
OurGame/Engine/Tool.h

- 마우스로 해당 메쉬가 몇 번인지 확인할 수 있는 기능 추가

Implement mesh select functions

---

OurGame/Client/PhysicsTestScene.cpp
OurGame/Client/PlayerMoveScript.cpp
OurGame/Engine/Collider.cpp
OurGame/Engine/Collider.h

Kinematic 충돌 구현

---

OurGame/Client/PhysicsTestScene.cpp
OurGame/Client/Player.cpp
OurGame/Client/PlayerMoveScript.cpp
OurGame/Client/PlayerMoveScript.h

Kinematic 충돌 개선

---

OurGame/Client/Client.vcxproj
OurGame/Client/Client.vcxproj.filters
OurGame/Client/ObstacleObject.cpp
OurGame/Client/ObstacleObject.h
OurGame/Client/PhysicsTestScene.cpp
OurGame/Client/PlayerMoveScript.cpp
OurGame/Client/TestRigidBodyScript.cpp
OurGame/Client/TestRigidBodyScript.h
OurGame/Engine/RigidBody.cpp
OurGame/Engine/RigidBody.h

ObstacleObject - RigidBody를 가지는 오브젝트
힘(AddForce), 회전(AddTorque), 힘+회전(AddForceAndTorque)을 가해주는 함수 추가

ObstacleObject클래스 + AddForce/Torque기능 추가

---

OurGame/Client/HallColliderCheckMap.cpp
OurGame/Engine/Collider.cpp
OurGame/Engine/Resources.cpp
OurGame/Engine/Resources.h

Implement capsule collider

---

OurGame/Client/AttackState.cpp
OurGame/Client/AttackState.h
OurGame/Client/EvasionState.cpp
OurGame/Client/EvasionState.h
OurGame/Client/Monster_Player_TestScene.cpp
OurGame/Client/MoveState.cpp
OurGame/Client/MoveState.h
OurGame/Client/Player.cpp
OurGame/Client/Player.h
OurGame/Client/PlayerMoveScript.cpp
OurGame/Client/State.h
OurGame/Client/pch.cpp
OurGame/Client/pch.h

플레이어 무브 키 입력처리 해결
플레이어 방향 fsm설정후 그방향에맞는 vec3 설정후
회피 기능 구현

플레이어 무브 작업 + 플레이어 회피 작업

---

OurGame/Client/Client.vcxproj.filters

Fix filter

---

OurGame/Client/DiningColliderCheckMap.cpp
OurGame/Client/MoveState.cpp
OurGame/Client/PlayerMoveScript.cpp
OurGame/Client/PlayerMoveScript.h
OurGame/Client/TitleScene.cpp
OurGame/Engine/Collider.cpp
OurGame/Engine/Collider.h
OurGame/Engine/RigidBody.cpp

Implement auto stepping functions

Implement auto stepping functions

---

OurGame/Client/DiningColliderCheckMap.cpp
OurGame/Client/DiningColliderCheckMap.h
OurGame/Engine/Engine.cpp
OurGame/Engine/Engine.vcxproj
OurGame/Engine/Engine.vcxproj.filters
OurGame/Engine/EnumDefine.h
OurGame/Engine/MultiRenderTarget.h
OurGame/Engine/RenderManager.cpp
OurGame/Engine/RenderManager.h
OurGame/Engine/Resources.cpp
OurGame/Engine/Scene.cpp
OurGame/Engine/Types.h
OurGame/Resources/Shader/player_slash.fx
OurGame/Resources/Shader/screeneffect.fx

Implement screen effect

---

OurGame/Client/ChangeStateCondition.cpp
OurGame/Client/ChangeStateCondition.h
OurGame/Client/Client.vcxproj
OurGame/Client/Client.vcxproj.filters
OurGame/Client/HeadRoller.cpp
OurGame/Client/HeadRoller.h
OurGame/Client/Monster.h
OurGame/Engine/AI.cpp
OurGame/Engine/AI.h
OurGame/Engine/BehaviorComposite.cpp
OurGame/Engine/BehaviorComposite.h
OurGame/Engine/BehaviorNode.cpp
OurGame/Engine/BehaviorNode.h

implement derived class from behavior node

implement derived class from behavior node

---

OurGame/Engine/MeshRenderer.cpp

Implement partial mesh rendering

Implement partial mesh rendering

---

OurGame/Client/IdleState.cpp
OurGame/Client/MoveState.cpp
OurGame/Client/MoveState.h
OurGame/Client/PlayerMoveScript.cpp
OurGame/Engine/Input.cpp
OurGame/Engine/Input.h

Implement hotkey in inputmanager

Implement hotkey in inputmanager

---

OurGame/Client/Bat.cpp
OurGame/Client/DiningColliderCheckMap.cpp
OurGame/Engine/Component.h
OurGame/Engine/Engine.vcxproj
OurGame/Engine/Engine.vcxproj.filters
OurGame/Engine/EnumDefine.h
OurGame/Engine/NavAgent.cpp
OurGame/Engine/NavAgent.h
OurGame/Engine/NavMesh.cpp
OurGame/Engine/NavMesh.h
OurGame/Engine/NavSceneComponent.cpp
OurGame/Engine/NavSceneComponent.h
OurGame/Engine/Navigation.cpp
OurGame/Engine/Navigation.h
OurGame/Engine/NavigationManager.cpp
OurGame/Engine/NavigationManager.h
OurGame/Engine/NavigationThread.cpp
OurGame/Engine/NavigationThread.h
OurGame/Engine/RenderManager.cpp
OurGame/Engine/SimpleMath.h
OurGame/Engine/SimpleMath.inl
OurGame/Engine/ThreadBase.cpp
OurGame/Engine/ThreadBase.h
OurGame/Engine/Types.h
OurGame/Resources/Shader/screeneffect.fx

Implemnet white in/out screen effect

Implemnet white in/out screen effect

---

OurGame/Engine/Engine.vcxproj
OurGame/Engine/Engine.vcxproj.filters
OurGame/Engine/EnumDefine.h
OurGame/Engine/NavMesh.h
OurGame/Engine/NavSceneComponent.cpp
OurGame/Engine/NavSceneComponent.h
OurGame/Engine/NavigationThread.cpp
OurGame/Engine/NavigationThread.h
OurGame/Engine/SemaphoreSync.cpp
OurGame/Engine/SemaphoreSync.h
OurGame/Engine/ThreadQueue.cpp
OurGame/Engine/ThreadQueue.h
OurGame/Engine/Types.h

NavMesh 20% complete

---

OurGame/Engine/Collider.cpp
OurGame/Engine/EnumDefine.h
OurGame/Engine/RigidBody.cpp
OurGame/Engine/RigidBody.h
OurGame/Engine/Types.h

Implement convex mesh

---

OurGame/Engine/Collider.cpp
OurGame/Engine/Collider.h
OurGame/Engine/CollisionManager.cpp
OurGame/Engine/CollisionManager.h
OurGame/Engine/Engine.cpp
OurGame/Engine/Physics.cpp
OurGame/Engine/Physics.h
OurGame/Engine/RigidBody.h

Implement overlap functions

---

OurGame/Client/Monster_Player_TestScene.cpp
OurGame/Engine/EnumDefine.h
OurGame/Engine/Physics.cpp
OurGame/Engine/RenderManager.cpp
OurGame/Engine/RenderManager.h
OurGame/Resources/Shader/screeneffect.fx

Implement hold color screen effect

---

OurGame/Client/Player.cpp
OurGame/Client/Player.h
OurGame/Client/PlayerMoveScript.cpp

Fix penetration & player ground check code

Fix penetration & player ground check code

---

OurGame/Client/Map.cpp
OurGame/Engine/Camera.cpp
OurGame/Engine/GameObject.cpp
OurGame/Engine/GameObject.h
OurGame/Engine/Light.cpp
OurGame/Engine/RenderManager.cpp
OurGame/Engine/Scene.cpp
OurGame/Engine/Scene.h
OurGame/Resources/Shader/lighting.fx

Implement enable point light placement

Implement enable point light placement

---

OurGame/Client/Monster_Player_TestScene.cpp
OurGame/Client/TitleScene.cpp
OurGame/Client/imgui.ini
OurGame/Engine/ButtonUI.cpp
OurGame/Engine/ButtonUI.h
OurGame/Engine/Engine.cpp
OurGame/Engine/Engine.vcxproj
OurGame/Engine/Engine.vcxproj.filters
OurGame/Engine/EnginePch.h
OurGame/Engine/EnumDefine.h
OurGame/Engine/GraphicsCore.cpp
OurGame/Engine/GraphicsCore.h
OurGame/Engine/Interface.cpp
OurGame/Engine/Interface.h
OurGame/Engine/InterfaceFont.cpp
OurGame/Engine/InterfaceFont.h
OurGame/Engine/InterfaceManager.cpp
OurGame/Engine/InterfaceManager.h
OurGame/Engine/RenderManager.cpp
OurGame/Engine/Resources.h
OurGame/Engine/SimpleMath.h
OurGame/Engine/Video.cpp
OurGame/Engine/Video.h

Develop ui framework

---

OurGame/Client/Bat.cpp
OurGame/Client/Client.vcxproj
OurGame/Client/Client.vcxproj.filters
OurGame/Client/Factory.h
OurGame/Client/Map.cpp
OurGame/Client/Monster.h
OurGame/Client/MonsterCrackScript.cpp
OurGame/Client/MonsterCrackScript.h
OurGame/Client/Player.cpp
OurGame/Client/Right2Map.cpp
OurGame/Client/TitleScene.cpp
OurGame/Engine/Light.cpp
OurGame/Engine/RenderManager.cpp
OurGame/Engine/Resources.cpp
OurGame/Engine/Scene.cpp
OurGame/Engine/Scene.h
OurGame/Resources/Shader/monster_deferred.fx
OurGame/Resources/Shader/paperburn.fx

Implement monster crack shader

Implement monster crack shader

---

OurGame/Client/HeadRoller.cpp
OurGame/Client/TitleScene.cpp
OurGame/Engine/RigidBody.cpp
OurGame/Engine/RigidBody.h
OurGame/Engine/Transform.cpp
OurGame/Engine/Transform.h

Implement graphic velocity

---

OurGame/Engine/Camera.cpp
OurGame/Engine/EnginePch.h
OurGame/Resources/Shader/lighting.fx

Implement lerp functions

---

OurGame/Client/BreakablePot.cpp
OurGame/Client/BreakablePot.h
OurGame/Client/BreakablePotCell.cpp
OurGame/Client/BreakablePotCell.h
OurGame/Client/PhysicsTestScene.cpp

항아리 복구 기능 구현(버그 있음)

---

OurGame/Engine/Animator.cpp
OurGame/Engine/Animator.h
OurGame/Engine/Mesh.h

Implement animation play speed

Implement animation play speed

---

OurGame/Engine/Animator.cpp

Fix animation speed logic

---

OurGame/Client/BreakablePot.cpp
OurGame/Client/BreakablePot.h
OurGame/Client/BreakablePotCell.cpp
OurGame/Client/BreakablePotCell.h
OurGame/Client/FireLamp.cpp
OurGame/Client/PhysicsTestScene.cpp
OurGame/Engine/Collider.cpp
OurGame/Engine/Collider.h
OurGame/Engine/Physics.h
OurGame/Library/Include/PhysX/geometry/PxGeometryQuery.h

Sweep 기능 구현

---

OurGame/Client/Bat.cpp
OurGame/Client/Client.vcxproj
OurGame/Client/Client.vcxproj.filters
OurGame/Client/Factory.h
OurGame/Client/MonsterCrackScript.cpp
OurGame/Client/MonsterHitScript.cpp
OurGame/Client/MonsterHitScript.h
OurGame/Engine/EnumDefine.h
OurGame/Engine/RenderManager.cpp
OurGame/Engine/RenderManager.h
OurGame/Resources/Shader/monster_deferred.fx
OurGame/Resources/Shader/screeneffect.fx

Implement camera shake effect

---

OurGame/Client/Bat.cpp
OurGame/Client/Monster.cpp
OurGame/Client/Monster.h
OurGame/Client/MonsterHitScript.cpp
OurGame/Engine/EnumDefine.h
OurGame/Engine/RenderManager.cpp
OurGame/Engine/RenderManager.h
OurGame/Resources/Shader/monster_deferred.fx
OurGame/Resources/Shader/screeneffect.fx

Implement monster hit shader

---

OurGame/Client/Right2Map.cpp
OurGame/Client/SlashGlareScript.cpp
OurGame/Client/SlashGlareScript.h
OurGame/Client/SwordGlareEffect.cpp
OurGame/Client/SwordGlareEffect.h
OurGame/Engine/Scene.cpp
OurGame/Engine/Scene.h
OurGame/Engine/SceneManager.cpp
OurGame/Engine/SceneManager.h

Fix scene life cycle

---

OurGame/Client/Right2Map.cpp
OurGame/Engine/CollisionManager.cpp
OurGame/Engine/CollisionManager.h
OurGame/Engine/GameObject.cpp
OurGame/Engine/Resources.cpp
OurGame/Resources/Shader/spider_web.fx

Implement collision clear functions

Implement collision clear functions

---

OurGame/Client/ArrowScript.h
OurGame/Client/FireLamp.h
OurGame/Client/Right2Map.cpp
OurGame/Client/SpiderWeb.cpp
OurGame/Client/SpiderWeb.h
OurGame/Engine/Engine.cpp
OurGame/Engine/Resources.cpp
OurGame/Engine/TimerObject.h
OurGame/Engine/Transform.cpp
OurGame/Engine/Transform.h
OurGame/Resources/Shader/spider_web.fx

Implement spider web shader

---

OurGame/Client/TitleScene.cpp
OurGame/Engine/Camera.h
OurGame/Engine/Material.cpp
OurGame/Engine/Material.h
OurGame/Engine/Mesh.cpp
OurGame/Engine/Mirror.cpp
OurGame/Engine/MultiRenderTarget.cpp
OurGame/Engine/MultiRenderTarget.h
OurGame/Engine/RenderManager.cpp
OurGame/Engine/RenderManager.h
OurGame/Engine/Scene.cpp
OurGame/Engine/Scene.h
OurGame/Engine/SceneManager.cpp
OurGame/Engine/Shader.cpp
OurGame/Engine/Shader.h
OurGame/Engine/Types.h
OurGame/Resources/Shader/forward.fx
OurGame/Resources/Shader/params.fx

Mirror 60% complete

---

OurGame/Client/BreakablePot.cpp
OurGame/Client/BreakablePot.h
OurGame/Client/BreakablePotCell.cpp
OurGame/Client/BreakablePotCell.h
OurGame/Client/PhysicsTestScene.cpp

항아리 파괴 방향 적용

---

OurGame/Client/BreakablePot.cpp
OurGame/Client/BreakablePot.h
OurGame/Engine/TimerObject.cpp
OurGame/Engine/TimerObject.h
OurGame/Engine/Transform.cpp
OurGame/Engine/Transform.h

항아리 파괴 연출 보강

---

OurGame/Client/Monster_Player_TestScene.cpp
OurGame/Engine/Engine.vcxproj
OurGame/Engine/Engine.vcxproj.filters
OurGame/Engine/GameObject.cpp
OurGame/Engine/Material.cpp
OurGame/Engine/Material.h
OurGame/Engine/Mirror.cpp
OurGame/Engine/Mirror.h
OurGame/Engine/RenderManager.cpp
OurGame/Engine/RenderManager.h
OurGame/Engine/Resources.cpp
OurGame/Engine/Shader.cpp
OurGame/Engine/Shader.h
OurGame/Engine/Types.h
OurGame/Resources/Shader/alpha.fx
OurGame/Resources/Shader/forward.fx
OurGame/Resources/Shader/params.fx

Implement mirror component

---

OurGame/Client/CameraHolder.cpp
OurGame/Client/CameraHolder.h
OurGame/Client/Client.vcxproj
OurGame/Client/Client.vcxproj.filters
OurGame/Client/EntranceHallMap.cpp
OurGame/Client/FocusingScript.cpp
OurGame/Client/FocusingScript.h
OurGame/Client/MainOfficeMap.cpp
OurGame/Client/Map.cpp
OurGame/Client/Map.h
OurGame/Client/MoveState.cpp
OurGame/Client/PlayerMoveScript.cpp
OurGame/Client/TitleScene.cpp
OurGame/Engine/Transform.cpp
OurGame/Engine/Transform.h

Implement smoothing camera

---

OurGame/Client/FocusingScript.cpp
OurGame/Client/FocusingScript.h
OurGame/Client/MainOfficeMap.cpp
OurGame/Client/Map.cpp
OurGame/Client/Map.h
OurGame/Client/Monster_Player_TestScene.cpp
OurGame/Client/Player.cpp
OurGame/Client/PlayerMoveScript.cpp
OurGame/Client/TitleScene.cpp
OurGame/Client/TitleScene.h
OurGame/Engine/RenderManager.cpp
OurGame/Engine/Scene.cpp
OurGame/Engine/Scene.h

Implement cutscene camera

---

OurGame/Client/CircleParticle.cpp
OurGame/Client/CircleParticle.h
OurGame/Client/Client.vcxproj
OurGame/Client/Client.vcxproj.filters
OurGame/Client/Player.cpp
OurGame/Engine/Engine.vcxproj
OurGame/Engine/Engine.vcxproj.filters
OurGame/Resources/Shader/circle_particle.fx

Implement circle particle

---

OurGame/Client/EntranceHallMap.cpp
OurGame/Client/Grimace.cpp
OurGame/Client/LeftSecretFightMap.cpp
OurGame/Engine/GameObject.cpp
OurGame/Engine/GameObject.h

Fix raycast bug

---

OurGame/Client/Factory.cpp
OurGame/Client/Factory.h
OurGame/Client/LeftSecretFightMap.cpp
OurGame/Client/RightMap.cpp
OurGame/Client/SpawnDoor.h
OurGame/Client/TitleScene.cpp
OurGame/Engine/Material.cpp
OurGame/Resources/Shader/paperburn.fx
OurGame/Resources/Shader/paperburn_spawn.fx

Fix monster spawn door

---

OurGame/Client/LeftSecretFightMap.cpp
OurGame/Client/Player.cpp
OurGame/Engine/ParticleSystem.cpp
OurGame/Engine/ParticleSystem.h
OurGame/Resources/Shader/spark_particle.fx

Fix spark particle

---

OurGame/Client/FocusingScript.cpp
OurGame/Client/TitleScene.cpp

Fix player follow camera speed

Fix player follow camera speed

---

OurGame/Client/CorridorRightMap.cpp
OurGame/Client/FocusingScript.cpp
OurGame/Client/Mage.cpp
OurGame/Client/MainOfficeMap.cpp
OurGame/Client/Player.cpp
OurGame/Client/Right2Map.cpp
OurGame/Client/RightMap.cpp
OurGame/Client/TitleScene.cpp
OurGame/Engine/Scene.cpp

RightMap -> CorriderMap -> Right2Map -> DiningColliderMap 연결

Map connection

---

OurGame/Client/BossMap.cpp
OurGame/Client/BossMap.h
OurGame/Client/CorridorRightMap.cpp
OurGame/Client/DiningColliderCheckMap.cpp
OurGame/Client/EntranceHallMap.cpp
OurGame/Client/FocusingScript.cpp
OurGame/Client/HallColliderCheckMap.cpp
OurGame/Client/LeftSecretFightMap.cpp
OurGame/Client/LeftSecretFightMap.h
OurGame/Client/LeftSecretTrialMap.cpp
OurGame/Client/LeftSecretTrialMap.h
OurGame/Client/Right2Map.cpp
OurGame/Client/RightMap.cpp
OurGame/Client/RightSecretPassageMap.cpp
OurGame/Client/TeleportZone.cpp
OurGame/Client/TeleportZone.h
OurGame/Client/TitleScene.cpp
OurGame/Engine/AudioSound.cpp
OurGame/Engine/RigidBody.h
OurGame/Engine/Scene.cpp
OurGame/Engine/Scene.h
OurGame/Engine/SceneManager.cpp

Connect all maps one way

---

OurGame/Client/LeftSecretFightMap.cpp
OurGame/Client/Player.cpp
OurGame/Client/TitleScene.cpp
OurGame/Engine/Input.cpp
OurGame/Engine/Input.h
OurGame/Engine/RigidBody.cpp

Apply player info to hot keys

---

OurGame/Client/HeadText.cpp
OurGame/Client/Right2Map.cpp

This reverts commit 6897d2d849e1c583c7e527d79d2728e5f91395b6.

Revert "Revert "에러 부분 제외 푸쉬""

---

OurGame/Client/BossLaser.cpp
OurGame/Client/BossLaser.h
OurGame/Client/LORD_BOSS.cpp
OurGame/Client/LaserLockOnScript.cpp
OurGame/Client/LaserLockOnScript.h
OurGame/Client/MoveState.cpp
OurGame/Client/Player.cpp
OurGame/Client/PlayerMoveScript.cpp
OurGame/Client/TitleScene.cpp
OurGame/Engine/Collider.h
OurGame/Engine/Resources.cpp
OurGame/Engine/Transform.cpp
OurGame/Engine/Transform.h

Player shadow bug fix

---

OurGame/Client/MonsterKeyScript.cpp
OurGame/Client/MoveState.cpp

Unicode bug fix

---

OurGame/Client/Client.vcxproj
OurGame/Client/Client.vcxproj.filters
OurGame/Client/LORD_BOSS.cpp
OurGame/Client/LaserLockOnScript.cpp
OurGame/Client/LaserLockOnScript.h
OurGame/Client/PaperBurnScript.cpp
OurGame/Client/PaperBurnScript.h
OurGame/Client/Player.cpp
OurGame/Client/PotDoor.cpp
OurGame/Client/PotDoor.h
OurGame/Engine/Engine.vcxproj
OurGame/Engine/Engine.vcxproj.filters
OurGame/Engine/Resources.cpp
OurGame/Resources/Shader/paperburn_potdoor.fx

Implement pot door

---

OurGame/Client/LORD_BOSS.cpp
OurGame/Client/LaserLockOnScript.cpp
OurGame/Client/LaserLockOnScript.h
OurGame/Engine/Collider.cpp
OurGame/Engine/Engine.vcxproj
OurGame/Engine/Engine.vcxproj.filters
OurGame/Engine/Resources.cpp
OurGame/Engine/Scene.cpp
OurGame/Resources/Shader/alpha_remove.fx

Fix debug mode bug

---

OurGame/Client/AIMoveState.cpp
OurGame/Client/Bus.cpp
OurGame/Client/CutSceneCameraMoveScript.cpp
OurGame/Client/CutSceneCameraMoveScript.h
OurGame/Client/MainOfficeMap.cpp
OurGame/Client/MainOfficeMap.h
OurGame/Client/MoveState.cpp
OurGame/Client/PauseState.cpp
OurGame/Client/Player.cpp
OurGame/Client/TextBox.cpp
OurGame/Client/TitleScene.cpp
OurGame/Client/TriggerObject.cpp

MainOffice NPC 클로즈업 추가

---

OurGame/Client/BossMap.cpp
OurGame/Client/CutSceneCameraMoveScript.cpp
OurGame/Client/CutSceneCameraMoveScript.h

BossMap 클리어 컷씬 구현

---

OurGame/Client/TriggerObject.cpp

Add Trigger remove event
